#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Create small, case-scoped self-tools without prebuilding a giant toolkit.

The factory creates one deterministic Python scaffold, a native Obsidian
manifest, and an audit stub. It does not call a model or execute the tool.
The investigator/agent edits the scaffold, validates it, then runs it through
case_tooling.py.
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path

try:
    from case_memory import append_event, write_snapshot
except ImportError:  # pragma: no cover
    append_event = None  # type: ignore
    write_snapshot = None  # type: ignore

TOOL_ID_RE = re.compile(r"^[A-Z][A-Z0-9._-]{2,63}$")
KINDS = {"parser", "analyzer", "linker", "simulator", "comparator", "graph-analyzer"}
ALLOWED_WRITES = ("08-Tooling", "05-Analysis", "02b-Exploration", "case-logs")


def safe_rel(case_root: Path, value: str) -> Path:
    path = (case_root / value).resolve()
    try:
        path.relative_to(case_root.resolve())
    except ValueError as exc:
        raise ValueError(f"path escapes case root: {value}") from exc
    return path


def validate_write_target(value: str) -> str:
    normalized = value.replace("\\", "/")
    if normalized.startswith("/") or any(part in {"", ".", ".."} for part in normalized.rstrip("/").split("/")):
        raise ValueError(f"writes-to contains unsafe path segments: {value}")
    normalized = normalized.rstrip("/")
    if not any(normalized == prefix or normalized.startswith(prefix + "/") for prefix in ALLOWED_WRITES):
        raise ValueError(f"writes-to outside allowed prefixes: {value}")
    return normalized + "/"


def py_scaffold(tool_id: str, kind: str, question: str) -> str:
    return f'''#!/usr/bin/env python3
"""Case-scoped {kind} scaffold: {tool_id}.

Generated by tool_factory.py. Keep the implementation small. Read only the
input paths passed by the manifest and write only to the declared run path.
Do not place credentials, network calls, or Evidence mutations here.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

TOOL_ID = {tool_id!r}
TOOL_KIND = {kind!r}
QUESTION = {question!r}


def transform(records: list[Any]) -> list[dict[str, Any]]:
    """Replace this identity transform with the smallest tested operation."""
    return [{{"index": index, "value": value, "status": "unreviewed"}} for index, value in enumerate(records)]


def main() -> int:
    parser = argparse.ArgumentParser(description=f"{{TOOL_ID}} — {{QUESTION}}")
    parser.add_argument("input", type=Path, help="JSON list inside the case workspace")
    parser.add_argument("output", type=Path, help="output path inside the declared tooling run directory")
    args = parser.parse_args()
    records = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        raise SystemExit("input must be a JSON list")
    result = {{
        "tool_id": TOOL_ID,
        "kind": TOOL_KIND,
        "question": QUESTION,
        "input_count": len(records),
        "status": "unreviewed",
        "records": transform(records),
    }}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def manifest_text(tool_id: str, kind: str, question: str, entrypoint: str, inputs: list[str], writes: list[str]) -> str:
    today = datetime.now(timezone.utc).date().isoformat()
    input_lines = "\n".join(f"  - {item}" for item in inputs) if inputs else "  []"
    write_lines = "\n".join(f"  - {item}" for item in writes)
    return f'''---
type: tool-manifest
status: draft
created: {today}
updated: {today}
tool-id: {tool_id}
version: 0.1.0
kind: {kind}
question: {json.dumps(question, ensure_ascii=False)}
runtime: python3
backend: auto
network: denied
entrypoint: {entrypoint}
inputs:
{input_lines}
writes-to:
{write_lines}
human-review: required
tests-passed: false
related-evidence: []
related-analysis: []
tags: [tooling, self-generated, {kind}]
---

# Tool Manifest — {tool_id}

## Build brief

- Question: {question}
- Kind: `{kind}`
- Generated by: `scripts/tool_factory.py`

## Validation before execution

```bash
python3 scripts/case_tooling.py validate <case-root> 08-Tooling/Manifests/{tool_id}.md
python3 scripts/case_tooling.py run <case-root> --manifest 08-Tooling/Manifests/{tool_id}.md --backend auto --run-id RUN-{tool_id}
```

The output is unreviewed analysis. It is not Evidence and cannot change a note status automatically.
'''


def audit_text(tool_id: str, kind: str) -> str:
    today = datetime.now(timezone.utc).date().isoformat()
    return f'''---
type: tool-audit
status: pending-human-review
created: {today}
updated: {today}
tool-id: {tool_id}
tool-version: 0.1.0
backend: none
network: denied
exit-code: null
source-hash: ""
input-hashes: []
output-hashes: []
tests-passed: false
human-review: pending
tags: [tooling, audit]
---

# Tool Audit — {tool_id}

- Generated scaffold kind: `{kind}`
- Build reason: 
- Fixture command: 
- Run ID: 
- Limitations: 

Do not mark this audit complete until static validation, fixture testing, hashes, and a human review are recorded.
'''


def create(args: argparse.Namespace) -> int:
    case_root = Path(args.case_root).resolve()
    if not TOOL_ID_RE.fullmatch(args.tool_id):
        raise SystemExit("tool-id must match ^[A-Z][A-Z0-9._-]{2,63}$")
    if args.kind not in KINDS:
        raise SystemExit(f"kind must be one of: {', '.join(sorted(KINDS))}")
    writes = [validate_write_target(item) for item in (args.write_to or ["08-Tooling/Runs/"])]
    entrypoint_rel = f"08-Tooling/Active/{args.tool_id}.py"
    entrypoint = safe_rel(case_root, entrypoint_rel)
    manifest_rel = f"08-Tooling/Manifests/{args.tool_id}.md"
    manifest = safe_rel(case_root, manifest_rel)
    audit = safe_rel(case_root, f"08-Tooling/Audits/{args.tool_id}.md")
    for path in (entrypoint, manifest, audit):
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not args.force:
            raise SystemExit(f"already exists: {path}; use --force only deliberately")
    inputs = [safe_rel(case_root, item).relative_to(case_root).as_posix() for item in (args.input or [])]
    entrypoint.write_text(py_scaffold(args.tool_id, args.kind, args.question), encoding="utf-8")
    manifest.write_text(manifest_text(args.tool_id, args.kind, args.question, entrypoint_rel, inputs, writes), encoding="utf-8")
    audit.write_text(audit_text(args.tool_id, args.kind), encoding="utf-8")
    if append_event is not None:
        append_event(
            case_root,
            "tool.scaffold",
            tool_event=True,
            tool_id=args.tool_id,
            kind=args.kind,
            question=args.question,
            entrypoint=entrypoint_rel,
            manifest=manifest_rel,
            audit=f"08-Tooling/Audits/{args.tool_id}.md",
            next_action="edit scaffold, add fixture, validate manifest",
            uncertainty="implementation is a scaffold and has not been tested",
        )
        if write_snapshot is not None:
            write_snapshot(case_root)
    print(f"created {entrypoint_rel}, {manifest_rel}, and 08-Tooling/Audits/{args.tool_id}.md")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a small case-scoped self-tool scaffold")
    sub = parser.add_subparsers(dest="command", required=True)
    create_parser = sub.add_parser("create")
    create_parser.add_argument("case_root")
    create_parser.add_argument("--tool-id", required=True)
    create_parser.add_argument("--kind", choices=sorted(KINDS), default="analyzer")
    create_parser.add_argument("--question", required=True)
    create_parser.add_argument("--input", action="append", default=[])
    create_parser.add_argument("--write-to", action="append", default=[])
    create_parser.add_argument("--force", action="store_true")
    create_parser.set_defaults(func=create)
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
